name: Check for Dependency Lock File

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-lock-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for package-lock.json
        run: |
          if [ ! -f package-lock.json ]; then
            echo "Error: package-lock.json is missing. Please run 'npm install' and commit the generated lock file."
            exit 1
          fi
